### ISSUE TITLE
OCaml compiler error

### ISSUE THREAD

**Issue by DemiMarie-parity** [runtimeverification/polkadot-verification#12]
`ocamlopt` is called with an invalid argument, causing an OCaml compilation error.

**Comment by ehildenb** [comment]
It's because we don't have an efficient garbage collector written for it yet. I don't know the full details (not on the LLVM backend team), but my understanding is that somehow it's not a precise as it could be about knowing "this memory is no longer needed".

So I guess the short answer is "memory leaks".

**Comment by ehildenb** [comment]
@dwightguth knows more, and is aware of the issues and consistently making progress on improving the state of it.

**Comment by hjorthjort** [comment]
Since the OCaml backend is not supported in this repo anymore, and is officially getting deprectaed on May 31, I think we can close this.
